---
joel:
  :host: federation-example.herokuapp.com
  :password: 'lol'
  :url: http://federation-example.herokuapp.com
  :name: Fed
  :paypal_email: jo+fed@easyjo.com
  :charity_id: 123
# ---
# james:
#   :host: james.local
#   :name: james
#   :paypal_email: james@example.com
#   :charity_id: 456
