---
orodio:
  :host: guarded-cove-7063.herokuapp.com
  :password: 'test'
  :url: https://guarded-cove-7063.herokuapp.com
  :name: orodio
  :paypal_email: james@bjorkman.ca
  :charity_id: 2050
# ---
# james:
#   :host: james.local
#   :name: james
#   :paypal_email: james@example.com
#   :charity_id: 456
