---
joel:
  :host: localhost
  :password: 'lol'
  :url: http://localhost:3000
  :name: joel
  :paypal_email: jo@example.com
  :charity_id: 123
# ---
# james:
#   :host: james.local
#   :name: james
#   :paypal_email: james@example.com
#   :charity_id: 456
